### PR TITLE
Added Dutch translation

### PR DESCRIPTION
**Pull request by Vistaus**
:-)

### CODE REVIEW

**Comment by lduboeuf** [comment]
thank you for your PR. But how did you get the app ?, we haven't published it to open store lol ;-)

**Comment by lduboeuf** [comment]
humm, i see 2 files, it should be only the `po/nl.po` something went wrong ?

**Comment by Vistaus** [comment]
I found it on your GitHub ;)

You're right about the two nl.po files: seems like GitHub accidentally committed the same thing twice in different locations (I did not put it in the root folder). Will fix.

**Comment by Vistaus** [comment]
Fixed :)

**Comment by lduboeuf** [comment]
thank you

**Pull request merged**
